---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAPA5bvwWaVjIkJlAPFSXdCR5sgNpyXdSl1O6OqntzyzGZZsbwmsq+YVqlhUV1NTiN0DWTWZ271sIIMhwzWysNazd/LpzQ8hII/OTpF2EFJoG5CVRrQZQdxqNGGhK/67mBLuYgTt1yV9i1gC/dxOiot+xKTSe2OFtaaEPlzb3pPU3ODY2pULEOCCneC6DeEb4qujDEhZk9B67aMhxDCM4/K4lnD4oadyK0s2bHcCzlQ5QxwWHdmIBRaLJbBwxrKMUfc/XpJkkPaFHQJPVGQvx7pmz6Rg7rlKMs3CinRytEFV7Cxqamfts8MjD7wzFIeWI4qo7XIk8PDFDAULZcRFsQsovAkDUSQSBMuzsLgAc7IqB3LL/WwFkEhUhkLLwcwrqPMKwAhnmEs95V3jinFJj4CvWoJnexG0uw7zga7QhtZjFudTcdS9fGFuKNgC/X5j1NpajisJ4Nr/ou1Ed3340/CpH8qrlL4XGSkjyZyI/byZhMZFJYVxol7FocETN5miaZFatjXdVWXYbdP7haM4gcD5VfePSlMyrlZRJO+oBVJNjTqoQxNMgVENIKSHofPXPy23lUHfhzGCEF5o3ZyEy4B2jiDy+wKI9wW/1AEuYDLL6xNx7mJP65LBfsbP+kuT/debFJvhmObhHdqMHXebbpYC6jbPij/9b+ijfhzh5xaWcGJqEjodjom1lz4hCpDMFH6iPr75bi3fJVL0n1ddzENAZ46TMLhHgvRla2s+Iw1ZtKDWFYd87KS
    admin-user: AgBftOyAc7MdpEcgGcByO6s2pZKXbAcRHf1/Ql9v6aVDznTGJ+18mIOJwc/A77m/K8eYX8drOPRXxR96qm8nUhiMUn0s6jFz7tuKWZXplojbsDcwrtRsFRwAJUwmRzctiAnAqjmBXFfXCLwkn9wJJM7NBjN6F6nkO3/BlcN2Xxc46DDgs58/6bzWrRp4P7cgMqMonp9i2XI9cMqV5EZC5lqCa+q4TktCNuM/GfiAUdO4eDRZB40I5jgFy0wFQ/pq8UkZcojPOvSo7DYV3hNgjBaI6xlFe2smo+sM8hhElbT5nNYB8EXJP3doVuFV3l9Y1n/9sb+9GpD2iLGWrhZ/clwjwufsiedDn9ngFFkCrw2PT+nWJlJA/tES3wZ6MlW+x9PQCJ2mzbVB2HjoXUbSKVU8WcACVNMZ7LaU1cL7LtW28UIznD89FNPUAdBoRx3Jgva+vrvGuyYM40znoNWdrPCgTObMkbQVcn6lRi74betp40ZN/RFtEbjiELdtPHbuXN9PDvKSahw2G/aIQRDRe4EnnezPfKFnMOyriIptEN59ySr/93ydzgJokSAGI5jISdzpheMsEJQIQiyK5Q9YmMVzW4c5booSYJ/DJGg2P2jpS2u2UJWTOGSxcy8Vq6ALmk+wQnK8GPKL01clpaWzmO3mpKjcL9ekUoUgy9wukI0z1wi/ZvKyISa+jyXBcCn8UNqTQ+LM6w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
