apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstreetlifting-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/openstreetlifting/openstreetlifting.git
      targetRevision: 6097609ac9437b7f2fd7c2f9552496ff3cb37e7b
      path: charts/
      helm:
        valueFiles:
          - values.yaml
          - $values/helm/openstreetlifting/values-staging.yaml
    - repoURL: https://github.com/dirdr/adrien_kubernetes_cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: osl-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
