apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstreetlifting
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/openstreetlifting/openstreetlifting.git
    targetRevision: main
    path: charts/openstreetlifting
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: osl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
